config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "countries#index"

  resources :countries do
    resources :projects
  end

  resources :charges
  resources :allprojects, only: :index
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :projects, dependent: :destroy
  validates :c_name, :presence => true
  validates :continent, :presence => true
  validates :c_description, :presence => true

  has_attached_file :attached_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attached_image, :content_type => /\Aimage\/.*\Z/

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :country

  validates_presence_of :total_needed
  validates :p_name, :presence => true
  validates :p_description, :presence => true

  has_attached_file :project_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :project_image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :projects
  validates_presence_of :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/allprojects_controller.rb
class AllprojectsController < ApplicationController

  def index
    @projects = Project.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @a = params["amount"].to_i
    @amount = @a * 100
    @project = Project.find(params[:project_id])
    if current_user
      @user = current_user
      @user.projects.push(@project)
    end
    @project.donation_count += 1
    @project.total_donated += @a
    @project.save

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    respond_to do |format|
      format.html { redirect_to root_path}
      format.js {redirect_to root_path}
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.order(:c_name)
    @AsiaCountries = Country.where(:continent => "Asia")
    @AfricaCountries = Country.where(:continent => "Africa")
    @NorthAmericaCountries = Country.where(:continent => "North-America")
    @SouthAmericaCountries = Country.where(:continent => "South-America")
    @AustraliaCountries = Country.where(:continent => "Australia")
    @EuropeCountries = Country.where(:continent => "Europe")
    @AntarticaCountries = Country.where(:continent => "Antartica")
  end

  def new
    if current_user && current_user.admin
      @country = Country.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      flash[:notice] = "Country saved."
      redirect_to countries_path
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def show
    @country = Country.find(params[:id])
    @countries = Country.order(:c_name)
  end

  def edit
    if current_user && current_user.admin
      @country = Country.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @country = Country.find(params[:id])
    if @country.update(country_params)
      flash[:notice] = "Your edits have been saved."
      redirect_to root_path
    else
      flash[:notice] = "Please try again."
      render :edit
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to countries_path
  end

  private
  def country_params
    params.require(:country).permit(:c_name, :continent, :c_description, :attached_image)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    if current_user && current_user.admin
      @country = Country.find(params[:country_id])
      @project = @country.projects.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @country = Country.find(params[:country_id])
    @project = @country.projects.new(project_params)
    if @project.save
      flash[:notice] = "Project saved."
      redirect_to root_path
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def show

    @country = Country.find(params[:country_id])
    @project = @country.projects.find(params[:id])
  end

  def edit
    if current_user && current_user.admin
      @country = Country.find(params[:country_id])
      @project = Project.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @country = Country.find(params[:country_id])
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Your edits have been saved."
      redirect_to root_path
    else
      flash[:notice] = "Please try again."
      render :edit
    end
  end

  def destroy
    @country = Country.find(params[:country_id])
    @project = @country.projects.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit(:p_name, :p_description, :project_image, :total_needed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/allprojects/index.html.erb
<div class="project">
<h1>All projects</h1>

<% @projects.each do |project| %>
  <div class="row">
    <div class="col-sm-12">
      <% country = Country.find(project.country_id) %>
      <%=link_to project.p_name, country_project_path(country, project) %>
      <p><%= country.c_name %></p>
      <% if project.p_image %>
        <%= image_tag (project.p_image), class:"country-image" %>
      <% elsif project.project_image_file_name %>
        <%= image_tag project.attached_image.url(:medium) %>
      <% else %>
      <%= image_tag ('missing.png'), class:"country-image" %>
      <% end %>
    </div>
  </div>
  <br />

<% end %>
</div>

app/views/charges/_form.html.erb
<%= form_tag charges_path do %>
  <%= hidden_field_tag 'project_id', params[:id] %>

  <%= label_tag "Amount you want to donate" %>
  <%= number_field_tag "amount", nil, min: 0 %>

  <article>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Donate!"
          ></script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%= @a %></strong>!</h2>

app/views/charges/new.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/countries/_country.html.erb
<div class="col-sm-5">
  <% if current_user && current_user.admin %>
    <div class="well admin-well country-well">
      <%= link_to "Edit Country", edit_country_path %> |
      <%= link_to "Add project", new_country_project_path(@country) %> |
      <%= link_to "Delete", country_path(@country),
              :data => {:confirm => "Are you sure you want to delete this project?",
              :method => "delete"} %>
    </div>
  <% end %>
  <h1><%= @country.c_name %></h1>

  <p><%= @country.c_description %></p>

  <% if @country.image %>
    <%= image_tag (@country.image), class:"country-image" %>
  <% elsif @country.attached_image_file_name  %>
    <%= image_tag (@country.attached_image_file_name), class:"country-image" %>
  <% else %>
    <%= image_tag ('missing.png'), class:"country-image" %>
  <% end %>

  <% if @country.projects.any? %>
    <% @country.projects.each do |project| %>
      <h3><%= link_to project.p_name, country_project_path(@country, project), remote: true %></h3>
      <p><%= project.p_description %></p>
    <% end %>
  <% end %>
</div>
<div class="col-sm-2">
  <div id="show_project_sidebar">
  </div>
</div>

app/views/countries/_country_sidebar.html.erb
<div class="col-sm-2 sidebar">
  <% @countries.each do |country| %>
    <h5><%= link_to country.c_name, country_path(country), remote: true %></h5>
    <% if country.image %>
      <%= link_to (image_tag (country.image)), country_path(country), class:"country-image thumbnail", remote:true %>
    <% elsif country.attached_image_file_name  %>
      <%= link_to (image_tag (country.attached_image_file_name)), country_path(country), class:"country-image thumbnail", remote:true %>
    <% else %>
      <%= link_to (image_tag('missing.png')), country_path(country), class:"country-image thumbnail", remote:true %>
    <% end %>
  <% end %>
</div>

app/views/countries/_form.html.erb
<div class="container">
  <div class="col-sm-6">
    <% render "layouts/errors", :object => @country %>

    <%= bootstrap_form_for @country do |f| %>
      <%= f.text_field :c_name, label: "Country name" %>
      <br>
      <%= f.text_area :c_description, label: "Describe this country" %>
      <br>
      <%= f.file_field :attached_image %>
      <br>
      <%= f.select(:continent, options_for_select([['North-America', 'North-America'], ['South-America', 'South-America'], ['Africa', 'Africa'], ['Asia', 'Asia'], ['Antarctica', 'Antarctica'], ['Europe', 'Europe'], ['Australia', 'Australia']]), :include_blank => true) %>
      <%= f.submit  class: "btn btn-success" %>
    <% end %>
    <br>
    <%= link_to "Return to home page", countries_path %>
  </div>
</div>

app/views/countries/edit.html.erb
<%= render 'form' %>

app/views/countries/index.html.erb
<div class="notice"></div>

<div class="row country-info">
  <div id="show_countries_sidebar">
  </div>
  <div id="show_countries">
  </div>
  <div id="show_projects">
  </div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="all_countries" class="col-sm-3">
    <% if @countries.any? %>
      <% @countries.each do |country| %>
        <h3><%= link_to country.c_name, country_path(country), remote: true %></h3>
        <% if country.image %>
          <%= image_tag (country.image), class:"country-image-smaller" %>
        <% else  %>
          <%= image_tag country.attached_image.url(:medium) %>
        <% end %>
      <% end %>
    <% end %>
  </div>

<div class="col-xs-9 map">
  <div class="map-wrapper">
    <div class="row">
      <div class="empty-grid col-xs-2 north-america" onClick ="$('#myModalNorthAmerica').modal('toggle')" id="popover1" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in North America">

      </div>

      <div class="empty-grid col-xs-2 north-america" onClick ="$('#myModalNorthAmerica').modal('toggle')" id="popover2" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in North America">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover3" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover4" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover5" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>

      <div class="empty-grid col-xs-2 north-america" onClick ="$('#myModalNorthAmerica').modal('toggle')" id="popover6" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in North America">

      </div>

      <div class="empty-grid col-xs-2 north-america" onClick ="$('#myModalNorthAmerica').modal('toggle')" id="popover7" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in North America">

      </div>

      <div class="empty-grid col-xs-2 europe" onClick ="$('#myModalEurope').modal('toggle')" id="popover8" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Europe">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover9" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover10" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>

      <div class="empty-grid col-xs-2 north-america" onClick ="$('#myModalNorthAmerica').modal('toggle')" id="popover11" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in North America">

      </div>

      <div class="empty-grid col-xs-2 south-america" onClick ="$('#myModalSouthAmerica').modal('toggle')" id="popover12" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in South America">

      </div>

      <div class="empty-grid col-xs-2 africa" onClick ="$('#myModalAfrica').modal('toggle')" id="popover13" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Africa">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover14" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>

      <div class="empty-grid col-xs-2 asia" onClick ="$('#myModalAsia').modal('toggle')" id="popover15" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Asia">

      </div>
      <div class="empty-grid col-xs-2">

      </div>
      <div class="empty-grid col-xs-2 south-america" onClick ="$('#myModalSouthAmerica').modal('toggle')" id="popover16" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in South America">
      </div>

      <div class="empty-grid col-xs-2 africa" onClick ="$('#myModalAfrica').modal('toggle')" id="popover17" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Africa">

      </div>

      <div class="empty-grid col-xs-2 australia" onClick ="$('#myModalAustralia').modal('toggle')" id="popover18" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Australia">

      </div>

      <div class="empty-grid col-xs-2 australia" onClick ="$('#myModalAustralia').modal('toggle')" id="popover19" data-trigger="hover"  data-container="body" data-toggle="popover" data-placement="top" data-content="View Projects in Australia">

      </div>
    </div>
  </div>
</div>
</div>

<!-- Button trigger modal -->
<div class="modal fade" id="myModalAsia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in Asia</h4>
      </div>
      <div class="modal-body">
        <% @AsiaCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalSouthAmerica" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in South America</h4>
      </div>
      <div class="modal-body">
        <% @SouthAmericaCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalNorthAmerica" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in North America</h4>
      </div>
      <div class="modal-body">
        <% @NorthAmericaCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalEurope" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in Europe</h4>
      </div>
      <div class="modal-body">
        <% @EuropeCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalAustralia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in Australia</h4>
      </div>
      <div class="modal-body">
        <% @AustraliaCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalAfrica" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in Africa</h4>
      </div>
      <div class="modal-body">
        <% @AfricaCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalAntartica" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Current Countries with Active Projects in Antartica</h4>
      </div>
      <div class="modal-body">
        <% @AntarticaCountries.each do |country| %>
          <%= link_to country.c_name, country_path(country), remote: true %> <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $('#popover1').popover();
  $('#popover2').popover();
  $('#popover3').popover();
  $('#popover4').popover();
  $('#popover5').popover();
  $('#popover6').popover();
  $('#popover7').popover();
  $('#popover8').popover();
  $('#popover9').popover();
  $('#popover10').popover();
  $('#popover11').popover();
  $('#popover12').popover();
  $('#popover13').popover();
  $('#popover14').popover();
  $('#popover15').popover();
  $('#popover16').popover();
  $('#popover17').popover();
  $('#popover18').popover();
  $('#popover19').popover();
</script>

app/views/countries/show.html.erb
<h1><%= @country.c_name %></h1>

<%= image_tag @country.attached_image.url(:medium) %>


<p><%= @country.c_description %></p>


<% if @country.projects.any? %>
  <% @country.projects.each do |project| %>
    <h3><%= link_to project.p_name, country_project_path(@country, project) %></h3>
    <%= image_tag project.project_image.url(:medium) %>
    <p><%= project.p_description %></p>
  <% end %>
<% end %>

<% if current_user && current_user.admin %>
  <p><%= link_to "Edit country page", edit_country_path %></p>
  <p><%= link_to "Add project", new_country_project_path(@country) %></p>
  <p><%= link_to "Delete country", country_path(@country),
          :data => {:confirm => "Are you sure you want to delete this project?",
          :method => "delete"} %></p>
<% end %>

<% if @country.projects.any? %>
  <% @country.projects.each do |project| %>
    <%= link_to project.p_name, country_project_path(@country, project) %>
  <% end %>
<% end %>
<br><%= link_to "Edit", edit_country_path(@country) %>

app/views/countries/show.js.erb
$('.country-info').show();
$("#show_countries_sidebar").html("<%= j render 'country_sidebar' %>");
$("#show_countries").html("<%= j render 'country' %>");
$("#all_countries").hide();
$(".map").hide();

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors</h3>
  <% object.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/_header.erb
<nav class="navbar navbar-default navbar-fixed-top">
   <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <%= image_tag('logo.jpg', class:'pull-left logo') %>
       <a href="/", class="navbar-brand">Global Giver</a>
      </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-left special-color">
         <li><%= link_to "Countries", countries_path %></li>
         <li><%= link_to "Projects", allprojects_path %></li>
           <% if current_user && current_user.admin %>
             <li><%= link_to "Add Country", new_country_path %></li>
         <% end %>
       </ul>
       <ul class="nav navbar-nav navbar-right special-color">
         <% if user_signed_in? %>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%>  <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><%= link_to "Edit Account", edit_user_registration_path %></a></li>
               <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
             </ul>
           </li>
         <% else %>
           <li><%= link_to "Sign up", new_user_registration_path %></li>
           <li><%= link_to "Sign in", new_user_session_path %></li>
         <% end %>
       </ul>
         </li>
     </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelGive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script:700' rel='stylesheet' type='text/css'></head>
<body>
    <%= render 'layouts/header' %>
  <div class="content">
    <div class="flash">
      <%= flash[:notice] %>
    </div>
      <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<div class="container">
  <h1><%= @country.c_name %></h1>

  <% render "layouts/errors", :object => @project %>

  <%= bootstrap_form_for [@country, @project] do |f| %>
    <%= f.text_field :p_name, label: "Project name" %>
    <br>
    <br>
    <%= f.text_area :p_description, label: "Describe this project" %>
    <br>
    <%= f.number_field :total_needed, label: "Total Amount Needed" %>
    <br>
    <%= f.file_field :project_image %>
    <br>
    <%= f.submit class: "btn btn-success" %>
  <% end %>
  <br>
  <%= link_to "Return to country page", country_path(@country) %>
</div>

app/views/projects/_project.html.erb
<div class="col-sm-5">
  <% if current_user && current_user.admin %>
    <div class="well admin-well">
      <%= link_to "Edit Project", edit_country_project_path(@country, @project) %> |
      <%= link_to "Delete Project", country_project_path(@country, @project),
              :data => {:confirm => "Are you sure you want to delete this project?",
              :method => "delete"} %>
    </div>
  <% end %>

  <h1><%= @project.p_name %></h1>
  <% if @project.p_image %>
    <%= image_tag (@project.p_image), class:"country-image" %>
  <% elsif @project.project_image_file_name %>
    <%= image_tag @project.attached_image.url(:medium) %>
  <% else %>
  <%= image_tag ('missing.png'), class:"country-image" %>
  <% end %>

  <h3><%= @country.c_name %></h3>
    <p>  Total Needed: $<%= @project.total_needed %></p>
    <p> Total Donated: $<%= @project.total_donated %></p>
    <p> Number of Donations: <%= @project.donation_count %></p>
  <p><%= @project.p_description %></p>

  <%= render partial: 'charges/form', project_id: @project.id %>
</div>

app/views/projects/_project_sidebar.html.erb
<div id="show_project_sidebar">
  <h1><%= @project.p_name %></h1>
  <% if @project.p_image %>
    <%= image_tag(@project.p_image, class:'thumbnail') %>
  <% end %>

  <h3><%= @country.c_name %></h3>
    <p>  Total Needed: $<%= @project.total_needed %></p>
    <p> Total Donated: $<%= @project.total_donated %></p>
    <p> Number of Donations: <%= @project.donation_count %></p>
  <p><%= @project.p_description %></p>

  <% if current_user && current_user.admin %>
    <p><%= link_to "Edit project", edit_country_project_path(@country, @project) %></p>
    <p><%= link_to "Delete project", country_project_path(@country, @project),
            :data => {:confirm => "Are you sure you want to delete this project?",
            :method => "delete"} %></p>
  <% end %>

  <%= render partial: 'charges/form', project_id: @project.id %>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>All projects</h1>
=======
<% @projects.each do |project| %>
  <%=link_to project.p_name, project_path(project) %>
<% end %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="well admin-well">
  <% if current_user && current_user.admin %>
    <%= link_to "Edit project", edit_country_project_path(@country, @project) %> |
    <%= link_to "Delete project", country_project_path(@country, @project),
            :data => {:confirm => "Are you sure you want to delete this project?",
            :method => "delete"} %></p>
  <% end %>
</div>
</div>

<div class="container">
  <div class="project">
    <h1><%= @project.p_name %></h1>
    <h3><%= @country.c_name %></h3>
    <div class="well project-well">
      <% if @project.p_image %>
        <%= image_tag (@project.p_image), class:"country-image" %>
      <% elsif @project.project_image_file_name %>
        <%= image_tag @project.attached_image.url(:medium) %>
      <% else %>
      <%= image_tag ('missing.png'), class:"country-image" %>
      <% end %>
        <p> Total Needed: $<%= @project.total_needed %></p>
        <p> Total Donated: $<%= @project.total_donated %></p>
        <p> Number of Donations: <%= @project.donation_count %></p>
        <p><%= @project.p_description %></p>
      </div>
    <%= render partial: 'charges/form', project_id: @project.id %>
  </div>

app/views/projects/show.js.erb
// $("#show_project_sidebar").html("<%= j render 'project_sidebar' %>");
$("#show_projects").html("<%= j render 'project' %>");